### ISSUE TITLE
你好，您的工作成果非常出色！请问如果在使用模型进行预测时lprmodel(data)输入数据data的geneous属性需要根据数据来源设置不同的值吗？

### ISSUE THREAD

**Issue by luanshuang** [SYSU-RoboticsLab/GAPR#2]
假设使用无人机采集的点云数据为data_a,地面机器人采集的点云数据为data_b，我需要将data_a[geneous]设置为1、data_b[geneous]设置为0吗？
感谢！

**Comment by yingruijie** [comment]
你好，是需要设置不同的geneous哈
