### ISSUE TITLE
evaluate

### ISSUE THREAD

**Issue by robot-wljywp** [SYSU-RoboticsLab/GAPR#4]
54行这里

        for sndx in source_indices:
            real_positive = np.intersect1d(
                dataset.get_positives(sndx),
                target_indices
            )

我测试空地点云之间的地点识别实验时，发现这个real_positive.shape[0]有可能是0，说明sndx没有和target_indice重叠的区域，但这种情况被加到了分母里，去计算准确率，我认为这样是错的。
68行计算准确率：        topN_recall[j] = float(topN_count[j]) / float(source_indices.shape[0])

**Comment by yingruijie** [comment]
你好，抱歉之前没看到这个问题。`real_positive` 如果为空，那么下面的 `recall_positive` 也是空，会让 `TopN Recall` 不能到 `100%`，比如说在地-空识别时，这是在论文里有提及的哈，这并不影响方法之间的比较。
